### ISSUE TITLE
Transaction returns incorrect error when sender does not have enough balance

### ISSUE THREAD

**Issue by shuse2** [LiskArchive/lisk-elements#1105]
### Expected behavior
Not enough balance error should reflect the original balance

### Actual behavior
Balance is shown for subtracted value.
This applies to both BaseTransaction and TransferTransaction
```
Account does not have enough LSK: 123L, balance: -0.1
```

### Steps to reproduce
1. Create a new TransferTransaction
2. input a sender who doesn't have enough balance for fee, or who does have balance for fee but not for amount
3. observe the error

### Which version(s) does this affect? (Environment, OS, etc...)
2.1-alpha.0

**Comment by SargeKhan** [comment]
On top of that, in case of low balance, the transaction response contains two errors with messages: `Account does not have enough LSK: 3078662141724708470L, balance: 0` and `Account does not have enough LSK: 3078662141724708470L, balance: -0.1`.
One of these errors is added in the base transaction and the other from transfer transaction.
