### ISSUE TITLE
Provide documention for scripts/init.sh

### ISSUE THREAD

**Issue by yatki** [LiskArchive/lisk-elements#1135]
### Expected behavior
We should have a documentation to guide developers to run `scripts/init.sh`.
- Don't forget to inform developers to rename `PORT_HERE` placeholder in `package.json.tmpl`. 

> PORT_HERE must be different than other package's port numbers.
### Actual behavior

We don't have documentation at the moment.

**Comment by shuse2** [comment]
Closing since we removed `scripts/init.sh`
