### ISSUE TITLE
Need a function to resolve peers domain names to their IP addresses

### ISSUE THREAD

**Issue by ishantiw** [LiskArchive/lisk-elements#1138]
### Expected behavior

In case domain names are used, resolve those to IP addresses.

### Actual behavior

There is no function to handle if a domain name is used by a peer. So we need to add this check in validation functions that sanitize peer info objects coming from the network.

**Comment by shuse2** [comment]
Decided that this should be done in the module level. As for a library, we decided not to have this feature for performance reason.
