### ISSUE TITLE
Multisignature transaction sets property with incorrect casing for multiMin and multiLifetime when applying/undoing transaction.

### ISSUE THREAD

**Issue by SargeKhan** [LiskArchive/lisk-elements#1140]
### Expected behavior
The properties defined for account related to multisignatures should be in camel case. 
### Actual behavior
The multisignature transaction assigns these properties to account in lower case.
### Steps to reproduce
Compare code with core.
### Which version(s) does this affect? (Environment, OS, etc...)
2.1.0

**Comment by shuse2** [comment]
It should update to 
```
readonly multiMin?: number;
readonly multiLifetime?: number;
```
