### ISSUE TITLE
Dapp transaction should allow type parameter to either be 0 or 1.

### ISSUE THREAD

**Issue by SargeKhan** [LiskArchive/lisk-elements#1148]
### Expected behavior
Dapp registration transaction should be allowed to have either type 0 or 1.
### Actual behavior
Dapp registration only accepts type with value = 0.

**Comment by shuse2** [comment]
@SargeKhan 
In the core logic, it seems it has to be 1
https://github.com/LiskHQ/lisk/blob/development/framework/src/modules/chain/logic/dapp.js#L130-L132
