### ISSUE TITLE
The format defined for "fee" property should allow 0 as value

### ISSUE THREAD

**Issue by SargeKhan** [LiskArchive/lisk-elements#1184]
### Expected behavior
The fee for all transactions in the genesis block is 0. Therefore, the validation for the format `fee` should pass when the fee is equal to 0. 
### Actual behavior
The schema validation fails for a transaction if the value of the property `fee` is zero.

**Comment by shuse2** [comment]
i think it make more sense to fail but ignored?

**Comment by shuse2** [comment]
Closing because genesis block is handled differently
