### ISSUE TITLE
Typings support for lisk-elements

### ISSUE THREAD

**Issue by Removed-5an** [LiskArchive/lisk-elements#684]
It would be very nice if we could have official @types for lisk-elements.

**Comment by willclarktech** [comment]
Rewriting in TypeScript would be covered by https://github.com/LiskHQ/lisk-elements/issues/417. Could you update the issue to be about TypeScript typings specifically? (Which we could provide regardless of whether we rewrite Elements in TypeScript or use Flow or neither.)
