### ISSUE TITLE
Cleaner separation of different kinds of logic for lisk-p2p 

### ISSUE THREAD

**Issue by jondubois** [LiskArchive/lisk-elements#958]
### Expected behavior

We need to keep strict separation of concerns across our source files to make sure that code stays readable and maintainable.

To maintain a consistent design philosophy, each source file should fit under exactly one of the following 3 categories:

- **Business objects**: Represents all the main objects that are used within the P2P library (class definitions).
- **Business operations (tasks/algorithms)**: Represents key operations supported by the P2P library; these are operations which cannot be implemented as a method of a class (e.g. because they are too long/complex, they operate on multiple kinds of objects, need to be tested independently, need to be replaceable...).
- **Validation and sanitisation operations**: Represents validation and sanitisation logic for objects that are passed to our code from the outside network. A validation function takes an object of unknown type as input and, if valid, will output an object of a known type. If the object is invalid, the function will throw an error.

How we should categorise our source files:

**Business objects**:
    - p2p.ts
    - peer_pool.ts
    - peer.ts

**Business operations (tasks/algorithms)**:
    - peer_discovery.ts
    - peer_selector.ts

**Validation and sanitisation operations**:
    - rpc_handler.ts 
    - response_handler.ts

### Actual behavior

One of our files (`rpc_handler.ts`) has overlapping responsibilities because the `getAllPeers(...)` function is not related to validation/sanitisation; this logic should be moved elsewhere.

----

Note that it is possible to implement the P2P library using only business objects but the two additional categories were added to:

- Allow important operations such as peer discovery and peer selection to be easily substituted and to be tested independently.
- Make it easier/less error-prone to migrate between different protocols (by having all the schema validation/sanitisation in a central place).

**Comment by jondubois** [comment]
Also, we should name our files to more accurately reflect the category under which they fit.

Suggestions:
- Rename `peer_selector.ts` to `peer_selection.ts` (to make it sound more like an operation rather than an object).
- Combine `response_handler.ts` and `rpc_handler.ts` into a single file and rename to `rpc_response_satinization.ts` (makes it more clear that it's related to sanitization; converting an unknown/unsafe type into a known/safe type).

**Comment by ishantiw** [comment]
> Also, we should name our files to more accurately reflect the category under which they fit.
> 
> Suggestions:
> 
> * Rename `peer_selector.ts` to `peer_selection.ts` (to make it sound more like an operation rather than an object).
> * Combine `response_handler.ts` and `rpc_handler.ts` into a single file and rename to `rpc_response_satinization.ts` (makes it more clear that it's related to sanitization; converting an unknown/unsafe type into a known/safe type).

I have moved functions from `rpc_handler.ts` to relevant files. I have added `fetchPeers()` in `Peer` class to get all the peers of a peer using `request()` for RPC call. Now we only have `response_handler.ts` as the file to have all the code related to sanitization. [Here is the related commit](https://github.com/LiskHQ/lisk-elements/pull/924/commits/0fdef35b8b387c66db9545284da5a1b9b33b7c98). 

Once we will all agree, I will rename the files (`peer_selector.ts` -> `peer_selection.ts` and `response_handler.ts` -> `response_handler_sanitization.ts`) in the Discovery [PR](https://github.com/LiskHQ/lisk-elements/pull/924).

**Comment by ishantiw** [comment]
I have renamed the files (peer_selector.ts -> peer_selection.ts and response_handler.ts -> response_handler_sanitization.ts) in the Discovery [PR](https://github.com/LiskHQ/lisk-elements/pull/924).

**Comment by shuse2** [comment]
Closing this issue, it's already solved by other PRs
